### ISSUE TITLE
Implementación con Firebase

### ISSUE THREAD

**Issue by jprojs** [softonic/instamaterial#1]
Hola,

Soy alumno del curso, ¿Podéis colgar la implementación con firebase?

Gracias

**Comment by JorgeDLS** [comment]
Hola Jprojs, 

Hemos colgado la implementación con Firebase, puedes encontrarla aquí 
[Rama Firebase](https://github.com/softonic/instamaterial/tree/firebase-implementation)

Un saludo y gracias.
